/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Sat Jan  6 13:56:26 2024.
 */

#ifndef POLICANBENT_H
#define POLICANBENT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define POLICANBENT_GB_ERROR_FRAME_ID (0x222u)
#define POLICANBENT_GB_DATA_FRAME_ID (0x422u)
#define POLICANBENT_GRETA_DATA_FRAME_ID (0x421u)
#define POLICANBENT_BOB_SRM_POWER_FRAME_ID (0x441u)
#define POLICANBENT_BOB_SRM_CADENCE_FRAME_ID (0x442u)
#define POLICANBENT_BOB_HS_SPEED_FRAME_ID (0x443u)
#define POLICANBENT_BOB_HS_DISPLACEMENT_FRAME_ID (0x444u)
#define POLICANBENT_BOB_HR_FRAME_ID (0x446u)
#define POLICANBENT_GRETA_ERROR_FRAME_ID (0x221u)
#define POLICANBENT_MIRIAM_GPS_DATA_FRAME_ID (0x501u)
#define POLICANBENT_MIRIAM_GPS_COORDS_FRAME_ID (0x502u)
#define POLICANBENT_MIRIAM_AIR_QUALITY_FRAME_ID (0x504u)
#define POLICANBENT_MIRIAM_TEMP_FRAME_ID (0x505u)
#define POLICANBENT_MIRIAM_GPS_OTHER_FRAME_ID (0x508u)
#define POLICANBENT_DUMBMS1_ERROR_FRAME_ID (0x280u)
#define POLICANBENT_DUMBMS2_ERROR_FRAME_ID (0x2a0u)
#define POLICANBENT_DUMBMS1_DATA_FRAME_ID (0x480u)
#define POLICANBENT_DUMBMS2_DATA_FRAME_ID (0x4a0u)

/* Frame lengths in bytes. */
#define POLICANBENT_GB_ERROR_LENGTH (1u)
#define POLICANBENT_GB_DATA_LENGTH (1u)
#define POLICANBENT_GRETA_DATA_LENGTH (2u)
#define POLICANBENT_BOB_SRM_POWER_LENGTH (2u)
#define POLICANBENT_BOB_SRM_CADENCE_LENGTH (2u)
#define POLICANBENT_BOB_HS_SPEED_LENGTH (2u)
#define POLICANBENT_BOB_HS_DISPLACEMENT_LENGTH (2u)
#define POLICANBENT_BOB_HR_LENGTH (1u)
#define POLICANBENT_GRETA_ERROR_LENGTH (1u)
#define POLICANBENT_MIRIAM_GPS_DATA_LENGTH (4u)
#define POLICANBENT_MIRIAM_GPS_COORDS_LENGTH (8u)
#define POLICANBENT_MIRIAM_AIR_QUALITY_LENGTH (8u)
#define POLICANBENT_MIRIAM_TEMP_LENGTH (2u)
#define POLICANBENT_MIRIAM_GPS_OTHER_LENGTH (2u)
#define POLICANBENT_DUMBMS1_ERROR_LENGTH (1u)
#define POLICANBENT_DUMBMS2_ERROR_LENGTH (1u)
#define POLICANBENT_DUMBMS1_DATA_LENGTH (5u)
#define POLICANBENT_DUMBMS2_DATA_LENGTH (5u)

/* Extended or standard frame types. */
#define POLICANBENT_GB_ERROR_IS_EXTENDED (0)
#define POLICANBENT_GB_DATA_IS_EXTENDED (0)
#define POLICANBENT_GRETA_DATA_IS_EXTENDED (0)
#define POLICANBENT_BOB_SRM_POWER_IS_EXTENDED (0)
#define POLICANBENT_BOB_SRM_CADENCE_IS_EXTENDED (0)
#define POLICANBENT_BOB_HS_SPEED_IS_EXTENDED (0)
#define POLICANBENT_BOB_HS_DISPLACEMENT_IS_EXTENDED (0)
#define POLICANBENT_BOB_HR_IS_EXTENDED (0)
#define POLICANBENT_GRETA_ERROR_IS_EXTENDED (0)
#define POLICANBENT_MIRIAM_GPS_DATA_IS_EXTENDED (0)
#define POLICANBENT_MIRIAM_GPS_COORDS_IS_EXTENDED (0)
#define POLICANBENT_MIRIAM_AIR_QUALITY_IS_EXTENDED (0)
#define POLICANBENT_MIRIAM_TEMP_IS_EXTENDED (0)
#define POLICANBENT_MIRIAM_GPS_OTHER_IS_EXTENDED (0)
#define POLICANBENT_DUMBMS1_ERROR_IS_EXTENDED (0)
#define POLICANBENT_DUMBMS2_ERROR_IS_EXTENDED (0)
#define POLICANBENT_DUMBMS1_DATA_IS_EXTENDED (0)
#define POLICANBENT_DUMBMS2_DATA_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/**
 * Signals in message GbError.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_gb_error_t {
    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gb_err_code;

    /**
     * Range: 0..16 (0..16 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gb_gear;
};

/**
 * Signals in message GbData.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_gb_data_t {
    /**
     * Range: 0..16 (0..16 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t gb_gear;
};

/**
 * Signals in message GretaData.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_greta_data_t {
    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t telek_battery;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rx_shifting;
};

/**
 * Signals in message BobSrmPower.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_bob_srm_power_t {
    /**
     * Range: 0..10000 (0..1000 W)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t srm_power;
};

/**
 * Signals in message BobSrmCadence.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_bob_srm_cadence_t {
    /**
     * Range: 0..10000 (0..1000 rpm)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t srm_cadence;
};

/**
 * Signals in message BobHsSpeed.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_bob_hs_speed_t {
    /**
     * Range: 0..20000 (0..200 km/h)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t hs_speed;
};

/**
 * Signals in message BobHsDisplacement.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_bob_hs_displacement_t {
    /**
     * Range: 0..200000 (0..20000 m)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t hs_displacement;
};

/**
 * Signals in message BobHR.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_bob_hr_t {
    /**
     * Range: 0..250 (0..250 bpm)
     * Scale: 1
     * Offset: 0
     */
    uint8_t heart_rate;
};

/**
 * Signals in message GretaError.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_greta_error_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t time_out_error;
};

/**
 * Signals in message MiriamGpsData.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_miriam_gps_data_t {
    /**
     * Range: 0..20000 (0..200 km/h)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t gps_speed;

    /**
     * Range: 0..20000 (0..20000 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t gps_displacement;
};

/**
 * Signals in message MiriamGpsCoords.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_miriam_gps_coords_t {
    /**
     * Range: -90000000..90000000 (-90..90 Â°)
     * Scale: 1e-06
     * Offset: 0
     */
    int32_t gps_latitude;

    /**
     * Range: -180000000..180000000 (-180..180 Â°)
     * Scale: 1e-06
     * Offset: 0
     */
    int32_t gps_longitude;
};

/**
 * Signals in message MiriamAirQuality.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_miriam_air_quality_t {
    /**
     * Range: 20000000..300000000 (200..3000 ppm)
     * Scale: 1e-05
     * Offset: 0
     */
    uint32_t co2_level;

    /**
     * Range: 0..400000000 (0..4000 level)
     * Scale: 1e-05
     * Offset: 0
     */
    uint32_t tvoc;
};

/**
 * Signals in message MiriamTemp.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_miriam_temp_t {
    /**
     * Range: 0..6000 (0..60 Â°C)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t temperature;
};

/**
 * Signals in message MiriamGpsOther.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_miriam_gps_other_t {
    /**
     * Range: 0..3000 (0..3000 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t altitude;
};

/**
 * Signals in message Dumbms1Error.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_dumbms1_error_t {
    /**
     * DumBMS LiPo undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat0_under_volt;

    /**
     * 3S slot 1 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat1_under_volt;

    /**
     * 3S slot 2 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat2_under_volt;

    /**
     * 3S slot 3 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat3_under_volt;

    /**
     * 3S slot 4 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat4_under_volt;
};

/**
 * Signals in message Dumbms2Error.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_dumbms2_error_t {
    /**
     * DumBMS LiPo undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat0_under_volt;

    /**
     * 3S slot 1 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat1_under_volt;

    /**
     * 3S slot 2 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat2_under_volt;

    /**
     * 3S slot 3 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat3_under_volt;

    /**
     * 3S slot 4 undervoltage detected
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bat4_under_volt;
};

/**
 * Signals in message Dumbms1Data.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_dumbms1_data_t {
    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat0_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat1_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat2_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat3_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat4_voltage;
};

/**
 * Signals in message Dumbms2Data.
 *
 * All signal values are as on the CAN bus.
 */
struct policanbent_dumbms2_data_t {
    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat0_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat1_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat2_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat3_voltage;

    /**
     * Range: 0..150 (0..15 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t bat4_voltage;
};

/**
 * Pack message GbError.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_gb_error_pack(
    uint8_t *dst_p,
    const struct policanbent_gb_error_t *src_p,
    size_t size);

/**
 * Unpack message GbError.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_gb_error_unpack(
    struct policanbent_gb_error_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_gb_error_gb_err_code_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_gb_error_gb_err_code_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_gb_error_gb_err_code_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_gb_error_gb_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_gb_error_gb_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_gb_error_gb_gear_is_in_range(uint8_t value);

/**
 * Pack message GbData.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_gb_data_pack(
    uint8_t *dst_p,
    const struct policanbent_gb_data_t *src_p,
    size_t size);

/**
 * Unpack message GbData.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_gb_data_unpack(
    struct policanbent_gb_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_gb_data_gb_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_gb_data_gb_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_gb_data_gb_gear_is_in_range(uint8_t value);

/**
 * Pack message GretaData.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_greta_data_pack(
    uint8_t *dst_p,
    const struct policanbent_greta_data_t *src_p,
    size_t size);

/**
 * Unpack message GretaData.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_greta_data_unpack(
    struct policanbent_greta_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_greta_data_telek_battery_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_greta_data_telek_battery_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_greta_data_telek_battery_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_greta_data_rx_shifting_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_greta_data_rx_shifting_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_greta_data_rx_shifting_is_in_range(uint8_t value);

/**
 * Pack message BobSrmPower.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_bob_srm_power_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_srm_power_t *src_p,
    size_t size);

/**
 * Unpack message BobSrmPower.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_bob_srm_power_unpack(
    struct policanbent_bob_srm_power_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_bob_srm_power_srm_power_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_bob_srm_power_srm_power_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_bob_srm_power_srm_power_is_in_range(uint16_t value);

/**
 * Pack message BobSrmCadence.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_bob_srm_cadence_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_srm_cadence_t *src_p,
    size_t size);

/**
 * Unpack message BobSrmCadence.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_bob_srm_cadence_unpack(
    struct policanbent_bob_srm_cadence_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_bob_srm_cadence_srm_cadence_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_bob_srm_cadence_srm_cadence_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_bob_srm_cadence_srm_cadence_is_in_range(uint16_t value);

/**
 * Pack message BobHsSpeed.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_bob_hs_speed_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hs_speed_t *src_p,
    size_t size);

/**
 * Unpack message BobHsSpeed.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_bob_hs_speed_unpack(
    struct policanbent_bob_hs_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_bob_hs_speed_hs_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_bob_hs_speed_hs_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_bob_hs_speed_hs_speed_is_in_range(uint16_t value);

/**
 * Pack message BobHsDisplacement.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_bob_hs_displacement_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hs_displacement_t *src_p,
    size_t size);

/**
 * Unpack message BobHsDisplacement.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_bob_hs_displacement_unpack(
    struct policanbent_bob_hs_displacement_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_bob_hs_displacement_hs_displacement_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_bob_hs_displacement_hs_displacement_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_bob_hs_displacement_hs_displacement_is_in_range(uint16_t value);

/**
 * Pack message BobHR.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_bob_hr_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hr_t *src_p,
    size_t size);

/**
 * Unpack message BobHR.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_bob_hr_unpack(
    struct policanbent_bob_hr_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_bob_hr_heart_rate_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_bob_hr_heart_rate_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_bob_hr_heart_rate_is_in_range(uint8_t value);

/**
 * Pack message GretaError.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_greta_error_pack(
    uint8_t *dst_p,
    const struct policanbent_greta_error_t *src_p,
    size_t size);

/**
 * Unpack message GretaError.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_greta_error_unpack(
    struct policanbent_greta_error_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_greta_error_time_out_error_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_greta_error_time_out_error_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_greta_error_time_out_error_is_in_range(uint8_t value);

/**
 * Pack message MiriamGpsData.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_miriam_gps_data_pack(
    uint8_t *dst_p,
    const struct policanbent_miriam_gps_data_t *src_p,
    size_t size);

/**
 * Unpack message MiriamGpsData.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_miriam_gps_data_unpack(
    struct policanbent_miriam_gps_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_miriam_gps_data_gps_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_gps_data_gps_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_gps_data_gps_speed_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_miriam_gps_data_gps_displacement_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_gps_data_gps_displacement_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_gps_data_gps_displacement_is_in_range(uint16_t value);

/**
 * Pack message MiriamGpsCoords.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_miriam_gps_coords_pack(
    uint8_t *dst_p,
    const struct policanbent_miriam_gps_coords_t *src_p,
    size_t size);

/**
 * Unpack message MiriamGpsCoords.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_miriam_gps_coords_unpack(
    struct policanbent_miriam_gps_coords_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t policanbent_miriam_gps_coords_gps_latitude_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_gps_coords_gps_latitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_gps_coords_gps_latitude_is_in_range(int32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int32_t policanbent_miriam_gps_coords_gps_longitude_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_gps_coords_gps_longitude_decode(int32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_gps_coords_gps_longitude_is_in_range(int32_t value);

/**
 * Pack message MiriamAirQuality.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_miriam_air_quality_pack(
    uint8_t *dst_p,
    const struct policanbent_miriam_air_quality_t *src_p,
    size_t size);

/**
 * Unpack message MiriamAirQuality.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_miriam_air_quality_unpack(
    struct policanbent_miriam_air_quality_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t policanbent_miriam_air_quality_co2_level_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_air_quality_co2_level_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_air_quality_co2_level_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t policanbent_miriam_air_quality_tvoc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_air_quality_tvoc_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_air_quality_tvoc_is_in_range(uint32_t value);

/**
 * Pack message MiriamTemp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_miriam_temp_pack(
    uint8_t *dst_p,
    const struct policanbent_miriam_temp_t *src_p,
    size_t size);

/**
 * Unpack message MiriamTemp.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_miriam_temp_unpack(
    struct policanbent_miriam_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_miriam_temp_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_temp_temperature_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_temp_temperature_is_in_range(uint16_t value);

/**
 * Pack message MiriamGpsOther.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_miriam_gps_other_pack(
    uint8_t *dst_p,
    const struct policanbent_miriam_gps_other_t *src_p,
    size_t size);

/**
 * Unpack message MiriamGpsOther.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_miriam_gps_other_unpack(
    struct policanbent_miriam_gps_other_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t policanbent_miriam_gps_other_altitude_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_miriam_gps_other_altitude_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_miriam_gps_other_altitude_is_in_range(uint16_t value);

/**
 * Pack message Dumbms1Error.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_dumbms1_error_pack(
    uint8_t *dst_p,
    const struct policanbent_dumbms1_error_t *src_p,
    size_t size);

/**
 * Unpack message Dumbms1Error.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_dumbms1_error_unpack(
    struct policanbent_dumbms1_error_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_error_bat0_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_error_bat0_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_error_bat0_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_error_bat1_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_error_bat1_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_error_bat1_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_error_bat2_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_error_bat2_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_error_bat2_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_error_bat3_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_error_bat3_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_error_bat3_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_error_bat4_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_error_bat4_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_error_bat4_under_volt_is_in_range(uint8_t value);

/**
 * Pack message Dumbms2Error.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_dumbms2_error_pack(
    uint8_t *dst_p,
    const struct policanbent_dumbms2_error_t *src_p,
    size_t size);

/**
 * Unpack message Dumbms2Error.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_dumbms2_error_unpack(
    struct policanbent_dumbms2_error_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_error_bat0_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_error_bat0_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_error_bat0_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_error_bat1_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_error_bat1_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_error_bat1_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_error_bat2_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_error_bat2_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_error_bat2_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_error_bat3_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_error_bat3_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_error_bat3_under_volt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_error_bat4_under_volt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_error_bat4_under_volt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_error_bat4_under_volt_is_in_range(uint8_t value);

/**
 * Pack message Dumbms1Data.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_dumbms1_data_pack(
    uint8_t *dst_p,
    const struct policanbent_dumbms1_data_t *src_p,
    size_t size);

/**
 * Unpack message Dumbms1Data.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_dumbms1_data_unpack(
    struct policanbent_dumbms1_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_data_bat0_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_data_bat0_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_data_bat0_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_data_bat1_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_data_bat1_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_data_bat1_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_data_bat2_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_data_bat2_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_data_bat2_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_data_bat3_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_data_bat3_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_data_bat3_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms1_data_bat4_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms1_data_bat4_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms1_data_bat4_voltage_is_in_range(uint8_t value);

/**
 * Pack message Dumbms2Data.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int policanbent_dumbms2_data_pack(
    uint8_t *dst_p,
    const struct policanbent_dumbms2_data_t *src_p,
    size_t size);

/**
 * Unpack message Dumbms2Data.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int policanbent_dumbms2_data_unpack(
    struct policanbent_dumbms2_data_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_data_bat0_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_data_bat0_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_data_bat0_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_data_bat1_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_data_bat1_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_data_bat1_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_data_bat2_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_data_bat2_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_data_bat2_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_data_bat3_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_data_bat3_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_data_bat3_voltage_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t policanbent_dumbms2_data_bat4_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double policanbent_dumbms2_data_bat4_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool policanbent_dumbms2_data_bat4_voltage_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
