/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Thu Jul 13 01:11:52 2023.
 */

#include <string.h>

#include "policanbent.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int policanbent_gb_error_pack(
    uint8_t *dst_p,
    const struct policanbent_gb_error_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->gb_err_code, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->gb_gear, 3u, 0xf8u);

    return (1);
}

int policanbent_gb_error_unpack(
    struct policanbent_gb_error_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->gb_err_code = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->gb_gear = unpack_right_shift_u8(src_p[0], 3u, 0xf8u);

    return (0);
}

uint8_t policanbent_gb_error_gb_err_code_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_gb_error_gb_err_code_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_gb_error_gb_err_code_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t policanbent_gb_error_gb_gear_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_gb_error_gb_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_gb_error_gb_gear_is_in_range(uint8_t value)
{
    return (value <= 16u);
}

int policanbent_gb_data_pack(
    uint8_t *dst_p,
    const struct policanbent_gb_data_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->gb_gear, 0u, 0x1fu);

    return (1);
}

int policanbent_gb_data_unpack(
    struct policanbent_gb_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->gb_gear = unpack_right_shift_u8(src_p[0], 0u, 0x1fu);

    return (0);
}

uint8_t policanbent_gb_data_gb_gear_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_gb_data_gb_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_gb_data_gb_gear_is_in_range(uint8_t value)
{
    return (value <= 16u);
}

int policanbent_rx_greta_pack(
    uint8_t *dst_p,
    const struct policanbent_rx_greta_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->rx_timeout, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->telek_battery, 1u, 0xfeu);
    dst_p[1] |= pack_left_shift_u8(src_p->rx_shifting, 0u, 0x03u);

    return (2);
}

int policanbent_rx_greta_unpack(
    struct policanbent_rx_greta_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->rx_timeout = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->telek_battery = unpack_right_shift_u8(src_p[0], 1u, 0xfeu);
    dst_p->rx_shifting = unpack_right_shift_u8(src_p[1], 0u, 0x03u);

    return (0);
}

uint8_t policanbent_rx_greta_rx_timeout_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_rx_greta_rx_timeout_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_rx_greta_rx_timeout_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t policanbent_rx_greta_telek_battery_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_rx_greta_telek_battery_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_rx_greta_telek_battery_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t policanbent_rx_greta_rx_shifting_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_rx_greta_rx_shifting_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_rx_greta_rx_shifting_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int policanbent_bob_srm_power_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_srm_power_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->srm_power, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->srm_power, 8u, 0xffu);

    return (2);
}

int policanbent_bob_srm_power_unpack(
    struct policanbent_bob_srm_power_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->srm_power = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->srm_power |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t policanbent_bob_srm_power_srm_power_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double policanbent_bob_srm_power_srm_power_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool policanbent_bob_srm_power_srm_power_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int policanbent_bob_srm_cadence_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_srm_cadence_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->srm_cadence, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->srm_cadence, 8u, 0xffu);

    return (2);
}

int policanbent_bob_srm_cadence_unpack(
    struct policanbent_bob_srm_cadence_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->srm_cadence = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->srm_cadence |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t policanbent_bob_srm_cadence_srm_cadence_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double policanbent_bob_srm_cadence_srm_cadence_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool policanbent_bob_srm_cadence_srm_cadence_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

int policanbent_bob_hs_speed_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hs_speed_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->hs_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->hs_speed, 8u, 0xffu);

    return (2);
}

int policanbent_bob_hs_speed_unpack(
    struct policanbent_bob_hs_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->hs_speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->hs_speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t policanbent_bob_hs_speed_hs_speed_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double policanbent_bob_hs_speed_hs_speed_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool policanbent_bob_hs_speed_hs_speed_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

int policanbent_bob_hs_displacement_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hs_displacement_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u16(src_p->hs_displacement, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->hs_displacement, 8u, 0xffu);

    return (2);
}

int policanbent_bob_hs_displacement_unpack(
    struct policanbent_bob_hs_displacement_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->hs_displacement = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->hs_displacement |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

uint16_t policanbent_bob_hs_displacement_hs_displacement_encode(double value)
{
    return (uint16_t)((value - 1.0) / 0.1);
}

double policanbent_bob_hs_displacement_hs_displacement_decode(uint16_t value)
{
    return (((double)value * 0.1) + 1.0);
}

bool policanbent_bob_hs_displacement_hs_displacement_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int policanbent_bob_hr_pack(
    uint8_t *dst_p,
    const struct policanbent_bob_hr_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->heart_rate, 0u, 0xffu);

    return (1);
}

int policanbent_bob_hr_unpack(
    struct policanbent_bob_hr_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->heart_rate = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t policanbent_bob_hr_heart_rate_encode(double value)
{
    return (uint8_t)(value);
}

double policanbent_bob_hr_heart_rate_decode(uint8_t value)
{
    return ((double)value);
}

bool policanbent_bob_hr_heart_rate_is_in_range(uint8_t value)
{
    return (value <= 250u);
}